### ISSUE TITLE
Title with localized tag are not processed

### ISSUE THREAD

**Issue by davidetoile** [winkelement/rs_tooltip#3]
if title fields display is activated and if it is declared in RS with multilingual tags, such as:

`~en-US:Product~fr:Produit`

Tooltip will not filter on current language and show
`~en-US:Product~fr:Produit`

Thank you

**Comment by winkelement** [comment]
Can you explain that a bit more? How can i reproduce? Thanks!

**Comment by winkelement** [comment]
Ok nevermind i think i fixed it :)

**Comment by davidetoile** [comment]
![2018-11-19_16-07-47](https://user-images.githubusercontent.com/2192706/48715449-55a2c880-ec15-11e8-8d65-310c225ea595.png)
Screenshot of the bug in the tooltip with `~en-US:Product~fr:Produit`

**Comment by winkelement** [comment]
Can you try again with the latest release/commit?

**Comment by davidetoile** [comment]
Solved, it rocks, thank you!
